[package]
name = "gooser"
version = "0.1.0"
authors = ["jrx <jerome+git@rouaix.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goose = "0.10.7"
log = "0.4"